branches-template:
  - main: "v{{major}}.{{minor}}.{{patch}}-{{date}}"
  - "feature/*": "{{ref-name}}-{{timestamp}}"
  - "release/*": "release-{{ref-name}}-{{timestamp}}.{{dist-tag}}"
  - tag: "v{{major}}.{{minor}}.{{patch}}"

dist-tags:
  - main: "latest"
  - "release/*": "next"
  - "feature/*": "beta"
  - tag: "stable"
