version: "3.8"

networks:
  colly-network:
    driver: bridge

volumes:
  postgres_data:

services:
  redis:
    image: redis:alpine
    container_name: colly-redis
    ports:
      - "6379:6379"
    networks:
      - colly-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
  postgres:
    image: postgres:15-alpine
    container_name: colly-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: colly-db
    ports:
      - "5432:5432"
    networks:
      - colly-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
