---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: {{ .Values.colly.name }}
    app.kubernetes.io/version: {{ .Values.colly.version }}
  name: {{ .Values.colly.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.colly.name }}
      app.kubernetes.io/version: {{ .Values.colly.version }}
  template:
    metadata:
      annotations:
        app.quarkus.io/quarkus-version: 3.18.2
      labels:
        app.kubernetes.io/name: {{ .Values.colly.name }}
        app.kubernetes.io/version: {{ .Values.colly.version }}
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: QUARKUS_DATASOURCE_JDBC_URL
              value: {{ .Values.colly.db.host }}
            - name: QUARKUS_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  key: username
                  name: {{ .Values.colly.name }}-secret
            - name: QUARKUS_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: {{ .Values.colly.name }}-secret
            - name: ENV_INSTANCES_REPO
              value: {{ .Values.colly.instancesRepo }}
          image: {{ .Values.colly.image }}
          imagePullPolicy: Always
          name: qubership-colly
          ports:
            - containerPort: {{ .Values.colly.ports.http }}
              name: http
              protocol: TCP
