{{- if not .Values.colly.envgeneInventoryService.cloudCoreSupport }}
---
kind: Secret
apiVersion: v1
metadata:
  name: {{ .Values.colly.envgeneInventoryService.serviceName }}-client-credentials
  labels:
    name: {{ .Values.colly.envgeneInventoryService.serviceName }}
    app.kubernetes.io/name: {{ .Values.colly.envgeneInventoryService.serviceName }}
    app.kubernetes.io/part-of: qubership-colly
    app.kubernetes.io/managed-by: {{ .Values.MANAGED_BY }}
data:
  name: {{ .Values.colly.envgeneInventoryService.idp.clientId | b64enc | quote }}
  password: {{ .Values.colly.envgeneInventoryService.idp.clientSecret | default "" | b64enc | quote }}
{{- end }}
