---
kind: Secret
apiVersion: v1
metadata:
  name: {{ .Values.colly.envgeneInventoryService.serviceName }}-secret
  labels:
    name: {{ .Values.colly.envgeneInventoryService.serviceName }}-secret
    app.kubernetes.io/name: {{ .Values.colly.envgeneInventoryService.serviceName }}-secret
    app.kubernetes.io/version: {{ .Chart.Version }}
data:
  username: {{ .Values.colly.envgeneInventoryService.redis.username | b64enc | quote }}
  password: {{ .Values.colly.envgeneInventoryService.redis.password | b64enc | quote }}
  gitToken: {{ .Values.colly.envgeneInventoryService.gitToken | b64enc | quote }}
