---
kind: Secret
apiVersion: v1
metadata:
  name: {{ .Values.colly.envgeneInventoryService.serviceName }}-secret
  labels:
    name: {{ .Values.colly.envgeneInventoryService.serviceName }}
    app.kubernetes.io/name: {{ .Values.colly.envgeneInventoryService.serviceName }}
    app.kubernetes.io/part-of: qubership-colly
    app.kubernetes.io/managed-by: {{ .Values.MANAGED_BY }}
data:
  username: {{ .Values.colly.envgeneInventoryService.redis.username | b64enc | quote }}
  password: {{ .Values.colly.envgeneInventoryService.redis.password | b64enc | quote }}
  gitToken: {{ .Values.colly.envgeneInventoryService.gitToken | b64enc | quote }}
