{{- if not .Values.colly.environmentOperationalService.cloudCoreSupport }}
---
kind: Secret
apiVersion: v1
metadata:
  name: {{ .Values.colly.environmentOperationalService.serviceName }}-client-credentials
  labels:
    name: {{ .Values.colly.environmentOperationalService.serviceName }}-client-credentials
    app.kubernetes.io/name: {{ .Values.colly.environmentOperationalService.serviceName }}-client-credentials
    app.kubernetes.io/version: {{ .Chart.Version }}
data:
  name: {{ .Values.colly.environmentOperationalService.idp.clientId | b64enc | quote }}
  password: {{ .Values.colly.environmentOperationalService.idp.clientSecret | default "" | b64enc | quote }}
{{- end }}
