---
kind: Secret
apiVersion: v1
metadata:
  name: {{ .Values.colly.environmentOperationalService.serviceName }}-secret
  labels:
    name: {{ .Values.colly.environmentOperationalService.serviceName }}
    app.kubernetes.io/name: {{ .Values.colly.environmentOperationalService.serviceName }}
    app.kubernetes.io/part-of: qubership-colly
    app.kubernetes.io/managed-by: {{ .Values.MANAGED_BY }}
data:
  username: {{ .Values.colly.environmentOperationalService.redis.username | b64enc | quote }}
  password: {{ .Values.colly.environmentOperationalService.redis.password | b64enc | quote }}
