---
kind: Secret
apiVersion: v1
metadata:
  name: {{ .Values.colly.name }}-secret
  labels:
    name: {{ .Values.colly.name }}-secret
    app.kubernetes.io/name: {{ .Values.colly.name }}-secret
    app.kubernetes.io/version: {{ .Values.colly.version }}
data:
  username: {{ .Values.colly.db.username | b64enc | quote }}
  password: {{ .Values.colly.db.password | b64enc | quote }}
