---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/quarkus-version: 3.18.2
  labels:
    app.kubernetes.io/name: {{ .Values.colly.name }}
    app.kubernetes.io/version: {{ .Values.colly.version }}
  name: {{ .Values.colly.name }}-service
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: {{ .Values.colly.ports.http }}
  selector:
    app.kubernetes.io/name: {{ .Values.colly.name }}
    app.kubernetes.io/version: {{ .Values.colly.version }}
  type: ClusterIP
