{{- if .Values.colly.uiService.uiEnabled }}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/quarkus-version: 3.27.2
  labels:
    name: {{ .Values.colly.uiService.serviceName }}
    app.kubernetes.io/name: {{ .Values.colly.uiService.serviceName }}
    app.kubernetes.io/part-of: qubership-colly
    app.kubernetes.io/managed-by: {{ .Values.MANAGED_BY }}
  name: {{ .Values.colly.uiService.serviceName }}
spec:
  ports:
    - name: web
      port: 8080
      protocol: TCP
      targetPort: {{ .Values.colly.uiService.ports.http }}
  selector:
    name: {{ .Values.colly.uiService.serviceName }}
  type: ClusterIP
{{- end }}
