name: Build Project

on:
  push:
  workflow_dispatch:
    inputs:
      version:
        required: true
        default: '1.0.0'
        type: string
        description: 'Release version (e.g., 1.0.0)'
      java-version:
        required: false
        type: string
        default: "21"
        description: 'Java version (e.g., 21)'
      build-docker:
        required: false
        type: boolean
        default: true
        description: 'Release docker image if there is Docker file'
      dry-run:
        required: false
        type: boolean
        default: false
        description: 'Dry run'
permissions:
  packages: write

jobs:
  mvn-build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
      - name: Display settings.xml
        run: cat ~/.m2/settings.xml
      - name: "Maven build"
        run: |
          mvn --batch-mode clean install
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_USER: ${{ github.actor }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
      - name: "Upload all Maven target directories"
        uses: actions/upload-artifact@v4
        with:
          name: 'target'
          path: '**/target'
          overwrite: 'true'

  perform-version:
    runs-on: ubuntu-latest
    needs: mvn-build
    outputs:
      metadata: "${{ steps.metadata.outputs.result }}"
      tags: "${{ steps.prepare_tags.outputs.tags }}"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create name
        uses: netcracker/qubership-workflow-hub/actions/metadata-action@main
        id: metadata
        with:
          configuration-path: .github/metadata-config.yml

      - name: Echo metadata
        run: echo "Metadata result ${{ steps.metadata.outputs.result }}" >> $GITHUB_STEP_SUMMARY

      - name: Prepare tags
        id: prepare_tags
        run: |
          BASE_TAG="${{ steps.metadata.outputs.result }}"
          EXTRA_TAG="${{ github.event.inputs.tags }}"
          if [ -n "$EXTRA_TAG" ]; then
            TAGS="${BASE_TAG}, ${EXTRA_TAG}"
          else
            TAGS="${BASE_TAG}"
          fi
          echo "tags=${TAGS}" >> $GITHUB_OUTPUT
          echo "tags: ${TAGS}" >> $GITHUB_STEP_SUMMARY

  docker-build:
    uses: netcracker/qubership-workflow-hub/.github/workflows/docker-publish.yml@main
    needs: perform-version
    with:
      ref: ${{ github.event.ref }}
      artifact-id: ${{ github.event.inputs.artifact-name || github.event.repository.name }}
      dry-run: false
      download-artifact: true
      tags: ${{ needs.perform-version.outputs.tags }}
