---
# Copied from https://github.com/Netcracker/.github/blob/main/workflow-templates/helm-charts-release.yaml and updated

# This workflow is used to release Helm charts and Docker images.
# It has a dry run stage to check the build process without actually publishing the artifacts.
# The workflow is triggered manually and allows the user to specify the release version.
# The workflow also creates a GitHub release after the deployment stage if the deployment is successful.
# The workflow uses the `netcracker/qubership-workflow-hub/actions/helm-charts-release` action to perform the release steps.
# The workflow requires the following inputs:
# - `release`: The release version to publish.
# - configuration file used for the release process: `.github/helm-charts-release-config.yaml`
# - Assets configuration file: `.github/assets-config.yml`
# - GitHub release drafter configuration file: `.github/release-drafter-config.yml`

name: Create Release
on:
  workflow_dispatch:
    inputs:
      release:
        description: 'Release version'
        required: true
        type: string
permissions:
  contents: write
  packages: write
run-name: ${{ github.repository }} Release ${{ github.event.inputs.release }}
concurrency:
  group: 'release'
  cancel-in-progress: false
jobs:
  check-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Check if tag exists
        id: check_tag
        uses: netcracker/qubership-workflow-hub/actions/tag-action@main
        with:
          tag-name: 'v${{ inputs.release }}'
          ref: ${{ github.ref }}
          create-tag: false
          check-tag: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  mvn-check-build:
    needs: [ check-tag ]
    uses: netcracker/qubership-workflow-hub/.github/workflows/maven-publish.yml@main
    with:
      maven-command: "--batch-mode clean package"
      upload-artifact: false
      ref: ${{ github.head_ref }}
    secrets:
      maven-token: ${{ secrets.GITHUB_TOKEN }}

  prepare-chart-release:
    needs: [mvn-check-build, check-tag]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: "Update versions in values"
        id: update-versions
        uses: netcracker/qubership-workflow-hub/actions/helm-charts-release@main
        with:
          release-version: ${{ inputs.release }}
          config-file: .github/helm-chart-release-config.yaml
        env:
          ${{ insert }}: ${{ vars }}

  tag:
    needs: [prepare-chart-release]
    runs-on: ubuntu-latest
    steps:
      - name: Create release tag
        uses: netcracker/qubership-workflow-hub/actions/tag-action@main
        with:
          tag-name: "v${{ inputs.release }}"
          ref: "release-${{ inputs.release }}"
          create-tag: true
          check-tag: false
  mvn-build:
    needs: [tag, prepare-chart-release]
    uses: netcracker/qubership-workflow-hub/.github/workflows/maven-publish.yml@main
    with:
      maven-command: "--batch-mode clean package"
      upload-artifact: true
      artifact-id: ${{ github.event.repository.name }}
      ref: ${{ github.head_ref }}
    secrets:
      maven-token: ${{ secrets.GITHUB_TOKEN }}

  docker-build:
    needs: [tag, mvn-build, prepare-chart-release]
    runs-on: ubuntu-latest
    steps:
      - name: Docker build
        uses: netcracker/qubership-workflow-hub/actions/docker-action@main
        with:
          ref: v${{ inputs.release }}
          download-artifact: true
          dry-run: false
          tags: "${{ inputs.release }}"
        env:
          GITHUB_TOKEN: ${{ github.token }}


  charts-release:
    needs: [tag, docker-build]
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: release-${{ inputs.release }}

      - name: Configure Git
        run: |
         git config user.name "$GITHUB_ACTOR"
         git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Run chart-releaser
        uses: netcracker/chart-releaser-action@main
        with:
          release_name_template: "v{{ .Version }}"
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

  github-release:
    needs: [charts-release]
    uses: netcracker/qubership-workflow-hub/.github/workflows/release-drafter.yml@main
    with:
      version: ${{ inputs.release }}
      publish: true
  upload-assets:
    needs: [github-release]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: v${{ inputs.release }}

      - name: Archive and Upload Assets
        uses: netcracker/qubership-workflow-hub/actions/archive-and-upload-assets@main
        with:
          config-path: '.github/assets-config.yaml'
          dist-path: './dist'
          upload: true
          ref: v${{ inputs.release }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
